# Generated by Django 5.2.6 on 2025-11-05 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_churchservice_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='churchservice',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='church_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
