# Generated by Django 5.0.6 on 2025-11-10 15:00

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser_profiles(apps, schema_editor):
    """
    Finds all superusers and creates a Profile for them if they don't have one.
    This ensures that superusers created via the command line can use the site
    without causing 500 errors due to a missing profile.
    """
    User = get_user_model()
    Profile = apps.get_model('accounts', 'Profile')
    
    for user in User.objects.filter(is_superuser=True):
        # Using get_or_create is safe and won't crash if a profile already exists.
        # It finds a profile for the user or creates one if it's missing.
        profile, created = Profile.objects.get_or_create(
            user=user,
            defaults={'role': 'admin', 'name': user.username} # Set default role and name
        )
        if created:
            print(f"Created missing profile for superuser: {user.username}")
        else:
            # Optional: If the profile existed but wasn't an admin, update it.
            if profile.role != 'admin':
                profile.role = 'admin'
                profile.save()
                print(f"Updated existing profile to admin for superuser: {user.username}")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_churchservice_members_profile_name_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser_profiles),
    ]
