# Generated by Django 5.2.6 on 2025-11-06 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_churchservice_members_profile_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], db_index=True, default='member', max_length=20),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='accounts_pr_role_fae1f3_idx'),
        ),
    ]
