# Generated by Django 5.2.6 on 2025-11-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_address_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wedding_anniversary',
            field=models.DateField(blank=True, help_text='For anniversary wishes', null=True),
        ),
    ]
