# Generated by Django 5.2.6 on 2025-11-06 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_wedding_anniversary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('service', 'Church Service'), ('prayer', 'Prayer Meeting'), ('fellowship', 'Fellowship'), ('outreach', 'Outreach'), ('training', 'Training/Workshop'), ('celebration', 'Celebration'), ('conference', 'Conference'), ('meeting', 'Meeting'), ('other', 'Other')], default='service', max_length=20)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('organizer', models.CharField(blank=True, max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_pattern', models.CharField(blank=True, help_text="e.g., 'Weekly on Sunday', 'Monthly first Saturday'", max_length=50)),
                ('max_attendees', models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
                'indexes': [models.Index(fields=['start_date', 'is_active'], name='accounts_ch_start_d_9e8100_idx'), models.Index(fields=['event_type'], name='accounts_ch_event_t_fa6df2_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.churchevent')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'phone')},
            },
        ),
    ]
