# Generated by Django 5.2.6 on 2025-11-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_churchevent_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='how_heard',
            field=models.CharField(blank=True, choices=[('evangelism', 'Evangelism/Street Outreach'), ('friend', 'Through a Friend/Family Member'), ('social_media', 'Social Media (Facebook, Instagram, etc.)'), ('website', 'Church Website'), ('passing_by', 'Passing By/One-time Visit'), ('relocation', 'Relocated to the Area'), ('invitation', 'Invited by Church Member'), ('other', 'Other')], help_text='How did you hear about our church?', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='how_heard_other',
            field=models.CharField(blank=True, help_text="Please specify if 'Other'", max_length=200, null=True),
        ),
    ]
