# Generated by Django 5.2.7 on 2025-11-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fix_superuser_profiles'),
        ('accounts', '0011_profile_how_heard_profile_how_heard_other'),
    ]

    operations = [
    ]
