# Generated by Django 5.2.6 on 2026-01-22 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('region_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('org', models.CharField(blank=True, max_length=200, null=True)),
                ('as_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_hosting', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP Geolocation',
                'verbose_name_plural': 'IP Geolocations',
                'indexes': [models.Index(fields=['ip_address'], name='accounts_ip_ip_addr_9f3c8b_idx'), models.Index(fields=['country'], name='accounts_ip_country_ea4c93_idx'), models.Index(fields=['city'], name='accounts_ip_city_7740be_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_phone', models.CharField(db_index=True, max_length=30)),
                ('member_name', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('geolocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ipgeolocation')),
            ],
            options={
                'verbose_name': 'Attendance Location',
                'verbose_name_plural': 'Attendance Locations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['member_phone', '-timestamp'], name='accounts_at_member__9a10b0_idx'), models.Index(fields=['ip_address'], name='accounts_at_ip_addr_96f359_idx'), models.Index(fields=['-timestamp'], name='accounts_at_timesta_0cbf09_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('geolocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ipgeolocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Location',
                'verbose_name_plural': 'Login Locations',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='accounts_lo_user_id_5ffd84_idx'), models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_3f7ed3_idx'), models.Index(fields=['-login_time'], name='accounts_lo_login_t_41b75e_idx')],
            },
        ),
    ]
