# Generated by Django 5.2.7 on 2026-01-22 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_ipgeolocation_attendancelocation_loginlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancelocation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Check-in Location', 'verbose_name_plural': 'Check-in Locations'},
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='device_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='device_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='distance_from_site',
            field=models.FloatField(blank=True, help_text='Distance from site in meters', null=True),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='gps_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='is_within_geofence',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Site/Location name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about this location')),
                ('site_type', models.CharField(choices=[('office', 'Office/Headquarters'), ('branch', 'Branch Location'), ('site', 'Work Site'), ('field', 'Field Location'), ('remote', 'Remote Work Zone'), ('event', 'Event Venue'), ('warehouse', 'Warehouse/Storage'), ('other', 'Other')], default='office', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate (-90 to 90)', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate (-180 to 180)', max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radius', models.PositiveIntegerField(default=100, help_text='Check-in radius in meters (10-10000m)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)])),
                ('address', models.CharField(blank=True, help_text='Street address', max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location accepts check-ins')),
                ('require_gps', models.BooleanField(default=True, help_text='Require GPS verification for check-in')),
                ('allow_remote', models.BooleanField(default=False, help_text='Allow check-ins outside geofence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_geofences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geofence Location',
                'verbose_name_plural': 'Geofence Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.geofence'),
        ),
        migrations.AddIndex(
            model_name='attendancelocation',
            index=models.Index(fields=['is_within_geofence'], name='accounts_at_is_with_988e23_idx'),
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['is_active', 'site_type'], name='accounts_ge_is_acti_c4f0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['latitude', 'longitude'], name='accounts_ge_latitud_042bba_idx'),
        ),
    ]
