# Generated by Django 5.2.6 on 2026-01-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_attendancelocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlocation',
            name='device_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loginlocation',
            name='device_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loginlocation',
            name='gps_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
    ]
