# Generated by Django 5.2.6 on 2026-01-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_gps_to_loginlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wedding_anniversary',
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Expected graduation year', null=True),
        ),
        migrations.AlterField(
            model_name='churchevent',
            name='event_type',
            field=models.CharField(choices=[('assembly', 'School Assembly'), ('lecture', 'Lecture/Class'), ('seminar', 'Seminar/Workshop'), ('excursion', 'Excursion/Field Trip'), ('training', 'Training/Workshop'), ('celebration', 'Celebration'), ('conference', 'Conference'), ('meeting', 'Meeting'), ('other', 'Other')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='how_heard',
            field=models.CharField(blank=True, choices=[('referral', 'School Referral'), ('friend', 'Through a Friend/Family Member'), ('social_media', 'Social Media (Facebook, Instagram, etc.)'), ('website', 'School Website'), ('passing_by', 'Passing By/Open House Visit'), ('relocation', 'Relocated to the Area'), ('invitation', 'Invited by Student/Staff'), ('other', 'Other')], help_text='How did you hear about our school?', max_length=50, null=True),
        ),
    ]
