# Generated by Django 5.2.6 on 2026-01-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_wedding_anniversary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wedding_anniversary',
            field=models.DateField(blank=True, help_text='Wedding anniversary date', null=True),
        ),
    ]
