# Generated by Django 5.2.6 on 2026-01-30 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_wedding_anniversary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wedding_anniversary',
        ),
    ]
