# Generated by Django 5.2.6 on 2025-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_memberattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchservice',
            name='code',
            field=models.CharField(default='DEFAULTCODE', help_text='Unique code for members to mark attendance.', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
