# Generated by Django 5.2.6 on 2025-11-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_churchservice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberattendance',
            name='phone',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='memberattendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='memberattendance',
            index=models.Index(fields=['phone', 'timestamp'], name='attendance__phone_de0617_idx'),
        ),
        migrations.AddIndex(
            model_name='memberattendance',
            index=models.Index(fields=['timestamp'], name='attendance__timesta_5219d8_idx'),
        ),
    ]
