# Generated by Django 5.2.6 on 2026-01-28 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_memberattendance_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchservice',
            name='code',
            field=models.CharField(help_text='Unique code for students to mark attendance.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='churchservice',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='school_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
